### ISSUE TITLE
Parameters are not matching

### ISSUE THREAD

**Issue by talatccan** [erayyildiz/LookupAnalyzerDisambiguator#1]
Hi, i've tried to run turkish-tagger on Windows and Ubuntu. First output was something like this:

`e7d45b3b4fae652e5a88fd91a88e1f155520da4075de1fc71655c91028510f11`

Docker was exiting after this output.

I changed a little on run command with the remove -d parameter and add -it parameter, i get error as following:

`[dynet] random seed: 403473904
[dynet] allocating memory: 512MB
[dynet] memory allocation done.
2019-07-16 08:07:56,997 - /usr/src/app/src/models.py - INFO - 112} - Loading Pre-Trained Model
Traceback (most recent call last):
  File "src/run.py", line 25, in <module>
    class APIHandler(BaseHandler):
  File "src/run.py", line 27, in APIHandler
    _morph_anlyzer = AnalysisScorerModel.create_from_existed_model("lookup_disambiguator_wo_suffix")
  File "/usr/src/app/src/models.py", line 326, in create_from_existed_model
    return AnalysisScorerModel(train_from_scratch=False, model_file_name=model_name)
  File "/usr/src/app/src/models.py", line 114, in __init__
    self.load_model(model_file_name, char_representation_len, word_lstm_rep_len)
  File "/usr/src/app/src/models.py", line 322, in load_model
    self.model.populate("resources/models/" + model_name + ".model")
  File "_dynet.pyx", line 1022, in _dynet.ParameterCollection.populate
  File "_dynet.pyx", line 1077, in _dynet.ParameterCollection.populate_from_textfile
RuntimeError: Dimensions of parameter /vanilla-lstm-builder/_0 looked up from file ({512,128}) do not match parameters to be populated ({512,64})`

How can i solve this problem?

**Comment by erayyildiz** [comment]
Ah yes, you are right. The parameter configuration was incorrect and I have fixed it now. Would you try again after pulling the last changes? Thanks.

**Comment by talatccan** [comment]
It worked. Thanks.

**Comment by erayyildiz** [comment]
Thanks for your feedback. I am closing this issue now. Feel free to ask any further questions.
